// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgSQfD3HqmeLI7OKb6c8SNzVrYhhRDEI',
    appId: '1:621490707063:web:edab07aec1b012d2744472',
    messagingSenderId: '621490707063',
    projectId: 'cards-f0837',
    authDomain: 'cards-f0837.firebaseapp.com',
    storageBucket: 'cards-f0837.firebasestorage.app',
    measurementId: 'G-5K5X6Z283G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQ-mBrEzeG-6EudcYYAD9naRN_NtAZ0M',
    appId: '1:621490707063:android:9ad4eecc30239bcd744472',
    messagingSenderId: '621490707063',
    projectId: 'cards-f0837',
    storageBucket: 'cards-f0837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrYCHIuBcrLcQJcDGVJOs-s7FtJTnw9e4',
    appId: '1:621490707063:ios:a1bc6dc101303cf8744472',
    messagingSenderId: '621490707063',
    projectId: 'cards-f0837',
    storageBucket: 'cards-f0837.firebasestorage.app',
    iosClientId: '621490707063-d0kiljnv51siq50gl7p53h0lpu2nvf23.apps.googleusercontent.com',
    iosBundleId: 'com.danielwells.cardgames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrYCHIuBcrLcQJcDGVJOs-s7FtJTnw9e4',
    appId: '1:621490707063:ios:78dd4b36e06520e9744472',
    messagingSenderId: '621490707063',
    projectId: 'cards-f0837',
    storageBucket: 'cards-f0837.firebasestorage.app',
    iosClientId: '621490707063-hhbkji4o5o659o1fqbllald24glcbpua.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgSQfD3HqmeLI7OKb6c8SNzVrYhhRDEI',
    appId: '1:621490707063:web:5c24cf4e8eeea086744472',
    messagingSenderId: '621490707063',
    projectId: 'cards-f0837',
    authDomain: 'cards-f0837.firebaseapp.com',
    storageBucket: 'cards-f0837.firebasestorage.app',
    measurementId: 'G-ZZD37Q9SZ5',
  );

}